spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    user: /user/**
security:
  oauth2:
    resource:
      userInfoUri: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/uaa/user
  ignored: /catalog/**
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
---
spring:
  profiles: development
  application:
    name: edge
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    user: /user/**
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
---
spring:
  profiles: docker
  application:
    name: edge
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    user: /user/**
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000